name: Warden Client Auto-Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # Versiyonu v4'e çekmek daha iyidir
        with:
          gradle-version: 8.10 # Sadece bu kalsın! 8.5 olanı sildik.

      - name: Build with Gradle
        run: gradle assemble --no-daemon
        env:
          JAVA_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=1g"
          GRADLE_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=1g"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1.${{ github.run_number }}
          name: Warden Client v1.1.${{ github.run_number }}
          body: "Warden Client 1.21.4 Sürümüne Taşındı!"
          draft: false
          prerelease: false
          files: "**/build/libs/*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
